services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:v2.2.2154
    container_name: suwayomi
    restart: unless-stopped
    networks:
      - proxy_net
      - media_net
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/New_York
      - SUWAYOMI_SERVER_DOWNLOAD_AS_CBZ=true

    volumes:
      # Persistent config storage on your array cache/pool
      - /mnt/user/appdata/suwayomi:/home/suwayomi/.local/share/suwayomi-server
      
      # Keep your media and download paths exactly the same
      - /mnt/user/data/media/manga:/data/manga
      - /mnt/user/data/downloads/complete:/downloads

      # Exact path to your manga share directory
      - /mnt/user/data/usenet/complete/manga:/data/manga
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.suwayomi.rule=Host(`manga.theblaskies.com`)"
      - "traefik.http.routers.suwayomi.entrypoints=websecure"
      - "traefik.http.services.suwayomi.loadbalancer.server.port=4567"
      - "traefik.docker.network=proxy_net"
      - "traefik.http.routers.suwayomi.tls.certresolver=cloudflare"


networks:
  proxy_net:
    external: true
  media_net:
    external: true
