services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns@sha256:5e61736b982b87d84a1120b4767c4deff0f2cc55ca3ee9dcb1dc58623039b5cb
    container_name: cloudflare-ddns
    restart: unless-stopped

    env_file:
      - .env

    environment:
      # DDNS only manages A records
      DOMAINS: theblaskies.com,*.theblaskies.com

      # Proxy everything EXCEPT Plex (handled via CNAME)
      PROXIED: "true"

      TTL: "300"
      IP_VERSION: ipv4
      UPDATE_INTERVAL: 300

    networks:
      - infra_net
networks:
  infra_net:
    external: true

