services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns@sha256:61013368c8f95981c0bb8bf56d962078d8b4e95724a554fa2dabb20d6e478097
    container_name: cloudflare-ddns
    restart: unless-stopped

    env_file:
      - .env

    environment:
      # DDNS only manages A records
      DOMAINS: theblaskies.com,*.theblaskies.com

      # Proxy everything EXCEPT Plex (handled via CNAME)
      PROXIED: "true"

      TTL: "300"
      IP_VERSION: ipv4
      UPDATE_INTERVAL: 300

    networks:
      - infra_net
networks:
  infra_net:
    external: true

