services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns@sha256:bc53b40b13c8b2a84e9b93c21f65fcd7d574b741014fb93912eb9efd93015aa2
    container_name: cloudflare-ddns
    restart: unless-stopped

    env_file:
      - .env

    environment:
      # DDNS only manages A records
      DOMAINS: theblaskies.com,*.theblaskies.com

      # Proxy everything EXCEPT Plex (handled via CNAME)
      PROXIED: "true"

      TTL: "300"
      IP_VERSION: ipv4
      UPDATE_INTERVAL: 300

    networks:
      - infra_net
networks:
  infra_net:
    external: true

