version: "3.8"

services:
  web:
    image: ghcr.io/hoarder-app/hoarder:latest@sha256:ae79300d55781be2afbc2cb5fd96a26a534516f6d88e3267c220cf78b18aa5c3
    container_name: karakeep-web
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/karakeep/data:/data
      # You do not need to map meili_data to the web container, 
      # only the meilisearch container needs access to its own data.
    environment:
      - NEXTAUTH_SECRET=${KARAKEEP_SECRET}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - NEXTAUTH_URL=https://karakeep.theblaskies.com
      - MEILI_ADDR=http://karakeep-search:7700
      - BROWSER_WEB_URL=ws://karakeep-chrome:3000
      - DATA_DIR=/data
      - MEILI_NO_ANALYTICS=true
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_net"
      - "traefik.http.routers.karakeep.rule=Host(`karakeep.theblaskies.com`)"
      - "traefik.http.routers.karakeep.entrypoints=websecure"
      - "traefik.http.routers.karakeep.tls=true"
      - "traefik.http.routers.karakeep.tls.certresolver=cloudflare"
      - "traefik.http.services.karakeep.loadbalancer.server.port=3000"

  chrome:
    image: zenika/alpine-chrome:with-puppeteer@sha256:ee10e24217aa27443e6b58da628f3b09ea9b814459915b8b62fe15a555f9692a
    container_name: karakeep-chrome
    user: root
    restart: unless-stopped
    entrypoint: /usr/bin/chromium-browser
    command:
      - --no-sandbox
      - --headless
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=3000
    environment:
      - CHROME_HEADLESS=1
    networks:
      - proxy_net

  meilisearch:
    image: getmeili/meilisearch:v1.53.1@sha256:8d6643d86d71fad6ad3cba92cde7ccfce9e4d6c384bda67598eb553571c32431
    container_name: karakeep-search
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_NO_ANALYTICS=true
    volumes:
      - /mnt/user/appdata/karakeep/meili_data:/meili_data
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
