services:
  kometa:
    image: kometateam/kometa:latest@sha256:b265e952fcc3931ac378601faf9e6e0d90bee104fc70d9002f59c8678bf00b87
    container_name: kometa
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/kometa:/config
      - /mnt/user/data/media/assets:/config/assets:rw

    networks:
      - media_net
      - proxy_net

networks:
  media_net:
    external: true

  proxy_net:
    external: true
