services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.4@sha256:b1b2021fe8f4004573e8d690dec6c7bb29cc44364572cf8510a05bf3a0ae2ded
    container_name: oauth2-proxy
    restart: unless-stopped

    env_file:
      - .env
    networks:
      - proxy_net
    labels:
      - traefik.enable=true
      - traefik.http.services.oauth2-proxy.loadbalancer.server.port=4180
networks:
  proxy_net:
    external: true
