services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.1@sha256:39f08531587045a5443db43299bf8495696c99ed8d0e1fdcbe60534f7c02ce14
    container_name: oauth2-proxy
    restart: unless-stopped

    env_file:
      - .env
    networks:
      - proxy_net
    labels:
      - traefik.enable=true
      - traefik.http.services.oauth2-proxy.loadbalancer.server.port=4180
networks:
  proxy_net:
    external: true
