services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.3@sha256:10a1165743a192e1940b4708fb9647027185ce11a681a1c5519b442ff7f1f561
    container_name: oauth2-proxy
    restart: unless-stopped

    env_file:
      - .env
    networks:
      - proxy_net
    labels:
      - traefik.enable=true
      - traefik.http.services.oauth2-proxy.loadbalancer.server.port=4180
networks:
  proxy_net:
    external: true
