services:
  cloudflared:
    image: cloudflare/cloudflared@sha256:072c067d25ccbe61d46e18f0d0723255f2bb5304f7317caa95b27031520ff92c
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
