http:
  routers:
    pelican-panel:
      rule: "Host(`pelican.theblaskies.com`)"
      entryPoints:
        - websecure
      service: pelican-panel-backend
      tls:
        certResolver: cloudflare

    pelican-wings:
      rule: "Host(`wings.theblaskies.com`)"
      entryPoints:
        - websecure
      service: pelican-wings-backend
      tls:
        certResolver: cloudflare

  services:
    pelican-panel-backend:
      loadBalancer:
        servers:
          - url: "http://10.69.30.30:8080" # <-- Nginx Web Panel

    pelican-wings-backend:
      loadBalancer:
        servers:
          - url: "http://10.69.30.30:8081" # <-- Wings Daemon
