services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest@sha256:f192e24e989f405c45c52c34ee6502c2edc4d4e1552bbff1a8c4321bc9b35b3b
    container_name: tdarr
    restart: unless-stopped

    env_file:
      - .env

    environment:
      serverIP: ${TDARR_SERVER_IP}
      serverPort: ${TDARR_SERVER_PORT}
      webUIPort: ${TDARR_WEBUI_PORT}

    volumes:
      - /mnt/user/appdata/tdarr/server:/app/server
      - /mnt/user/data/media:/media
      - /mnt/cache/temp/tdarr-temp:/temp

    networks:
      - media_net
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.rule=Host(`tdarr.theblaskies.com`)
      - traefik.http.routers.tdarr.entrypoints=websecure
      - traefik.http.routers.tdarr.tls.certresolver=cloudflare
      - traefik.http.services.tdarr.loadbalancer.server.port=8265

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest@sha256:6359991d297ec23e2a5fe3a6b5b19c65d9eabdc63172d2cbe6aa576bbe5356c2
    container_name: tdarr-node
    restart: unless-stopped

    env_file:
      - .env

    environment:
      nodeName: ${TDARR_NODE_NAME}
      serverIP: tdarr
      serverPort: ${TDARR_SERVER_PORT}

    volumes:
      - /mnt/user/appdata/tdarr/node:/app/configs
      - /mnt/user/data/media:/media
      - /mnt/cache/temp/tdarr-temp:/temp

    runtime: nvidia

    networks:
      - media_net

networks:
  media_net:
    external: true
  proxy_net:
    external: true
