services:
  docker-socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy@sha256:1f5038b54f06c3e18422902cf00ba21803d1c97805aae032e5e6673d532d3459
    container_name: docker-socket-proxy
    restart: unless-stopped

    environment:
      CONTAINERS: 1
      SERVICES: 1
      NETWORKS: 1
      TASKS: 1
      EVENTS: 1
      INFO: 1

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - proxy_net


  traefik:
    image: traefik@sha256:03650d05c2ce54959c1016c879371d20ad303ecbaecc1621f6ed231cd2e0b516
    container_name: traefik
    restart: unless-stopped

    env_file:
      - .env

    command:
      - --configFile=/etc/traefik/traefik.yml

    ports:
      - "80:80"
      - "443:443"

    volumes:
      # Static config
      - /mnt/user/appdata/komodo/repos/Blaskielab/stacks/infra/traefik/traefik.yml:/etc/traefik/traefik.yml:ro

      # Dynamic config (Git-managed)
      - /mnt/user/appdata/komodo/repos/Blaskielab/stacks/infra/traefik/dynamic:/etc/traefik/dynamic:ro

      # ACME storage
      - /mnt/user/appdata/traefik/acme:/etc/traefik/acme

    networks:
      - proxy_net

  error-pages:
    image: ghcr.io/tarampampam/error-pages:latest@sha256:b8ded6f847df91075429cf79cb9491bfd7d96de69936555498a2ff0614e003e4
    container_name: error-pages
    restart: unless-stopped
    environment:
      - TEMPLATE_NAME=shuffle # Pick your aesthetic: ghost, l33t, matrix, connection, etc.
      - SHOW_DETAILS=true
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      # This registers it globally for Traefik's file provider to hook into
      - "traefik.http.services.error-pages-service.loadbalancer.server.port=8080"

networks:
  proxy_net:
    external: true
