services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.17@sha256:60f3b6b5c7647ba2bafd81163acfe34b11117b9b834ebd7fbcc3e5f1b309c7ef
    container_name: sonarr
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/sonarr:/config
      - /mnt/user/data:/data
      - /mnt/user/data/recycle-bin:/data/recycle-bin
    networks:
      - media_net
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.theblaskies.com`)
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.tls.certresolver=cloudflare
      - traefik.http.services.sonarr.loadbalancer.server.port=8989

networks:
  media_net:
    external: true
  proxy_net:
    external: true
