services:
  plex:
    image: ghcr.io/linuxserver/plex:latest@sha256:c5e295f023b4e92b3ca467626dbc2ba8a9b5e53934810df74d99c14e38ae1857
    container_name: plex
    restart: unless-stopped
    runtime: nvidia

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/plex:/config
      - /mnt/user/data/media:/media
    tmpfs:
      - /transcode:size=16G

    networks:
      br0.20:                      # Plugs directly into your 10.69.20.xx Services VLAN
        ipv4_address: 10.69.20.50  # Fixed IP for unthrottled local client discovery
      proxy_net:                   # Internal Docker bridge network for Traefik routing

    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_net  # Forces Traefik to route over the proxy bridge, ignoring the VLAN IP
      - traefik.http.routers.plex.rule=Host(`plex.theblaskies.com`)
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.tls.certresolver=cloudflare
      - traefik.http.services.plex.loadbalancer.server.port=32400

networks:
  br0.20:
    name: br0.20                   # Matches Unraid's exact physical interface name
    external: true                 # Tells Docker to use Unraid's existing network
  proxy_net:
    external: true                 # Connects to your existing Traefik network
