services:
  bumper:
    image: bmartin5692/bumper:latest
    container_name: bumper
    restart: unless-stopped
    networks:
      # Use the exact name of the network as it appears in Unraid 'Docker' tab
      br0.30: 
        ipv4_address: 10.69.30.4
      infra_net:
    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - BUMPER_ANNOUNCE_IP=10.69.30.4
      - BUMPER_LISTEN=0.0.0.0
      - LOG_TO_STDOUT=true
      - BUMPER_DEBUG=true
      - BUMPER_DATA=/bumper/data
      - BUMPER_CERT=/bumper/data/certs/bumper.crt
      - BUMPER_KEY=/bumper/data/certs/bumper.key
      - BUMPER_CA=/bumper/data/certs/ca.crt

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/bumper/config:/bumper/data
      - /mnt/user/appdata/bumper/certs:/bumper/data/certs

    labels:
      - "traefik.enable=false"

networks:
  # This tells Docker the VLAN 30 bridge is managed by the OS
  br0.30:
    external: true
  infra_net:
    external: true
