services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.6.1@sha256:762f802274598da27255b2e5778f262b2b71b355a23e3812d9ee1520f8dbe37c
    container_name: bazarr
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/bazarr:/config
      - /mnt/user/data/media:/media

    networks:
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.theblaskies.com`)
      - traefik.http.routers.bazarr.entrypoints=websecure
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.routers.bazarr.tls.certresolver=cloudflare
      - traefik.http.services.bazarr.loadbalancer.server.port=6767

networks:
  proxy_net:
    external: true
