services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    networks:
      - infra_net
      - proxy_net
    ports:
      - "13378:80"
    volumes:
      - /mnt/user/appdata/audiobookshelf/config:/config
      - /mnt/user/appdata/audiobookshelf/metadata:/metadata
      - /mnt/user/data:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.theblaskies.com`)"
      - "traefik.http.routers.audiobookshelf.entrypoints=websecure"
      - "traefik.http.routers.audiobookshelf.tls=true"
      - "traefik.http.routers.audiobookshelf.tls.certresolver=cloudflare"
      - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"

networks:
  infra_net:
    external: true
  proxy_net:
    external: true
