services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    restart: unless-stopped
    # Use init to handle zombie processes correctly in the new image
    init: true

    env_file:
      - .env

    volumes:
      - /mnt/user/appdata/seerr:/app/config

    networks:
      - media_net
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.http.routers.seerr.rule=Host(`requests.theblaskies.com`)
      - traefik.http.routers.seerr.entrypoints=websecure
      - traefik.http.routers.seerr.tls.certresolver=cloudflare
      - traefik.http.services.seerr.loadbalancer.server.port=5055

networks:
  media_net:
    external: true
  proxy_net:
    external: true
