services:
  unpackerr:
    image: ghcr.io/unpackerr/unpackerr:v0.16.1@sha256:406586865431b40b29353d899fb75a788f5384743f7f381444db5fe55d206914
    container_name: unpackerr
    restart: unless-stopped
    user: "1002:281"

    env_file:
      - .env

    volumes:
      - /mnt/user/data:/data

    networks:
      - media_net
networks:
   media_net:
     external: true
