services:
  grimmory:
    image: grimmory/grimmory:latest@sha256:c83dcb59975c9a680ecdf84d60e7e5c9b05200818bab8794f4d84a7e008a549a
    container_name: grimmory
    restart: unless-stopped
    networks:
      - proxy_net
      - media_net
    security_opt:
      - no-new-privileges:true
    environment:
      - USER_ID=${APP_USER_ID:-99}
      - GROUP_ID=${APP_GROUP_ID:-100}
      - TZ=${TZ:-America/New_York}
      - DATABASE_URL=jdbc:mariadb://mariadb:3306/${MYSQL_DATABASE:-grimmory}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - BOOKLORE_PORT=${BOOKLORE_PORT:-8000}
      # Required for Unraid to handle "moves" instead of "copies"
      - DISK_TYPE=LOCAL 
    volumes:
      - /mnt/user/appdata/grimmory/data:/app/data
      # PERMANENT LIBRARIES: One mount for all media
      - /mnt/user/data/media:/books
      - /mnt/user/data/usenet/complete/manga:/bookdrop/manga
      - /mnt/user/data/usenet/complete/comics:/bookdrop/comics
      - /mnt/user/data/usenet/complete/books:/bookdrop/books

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grimmory.rule=Host(`grimmory.theblaskies.com`)"
      - "traefik.http.routers.grimmory.entrypoints=websecure"
      - "traefik.http.routers.grimmory.tls.certresolver=cloudflare"
      - "traefik.http.services.grimmory.loadbalancer.server.port=8000"

networks:
  proxy_net:
    external: true
  media_net:
    external: true
