version: "3.8"

services:
  apprise:
    image: lscr.io/linuxserver/apprise-api:latest@sha256:3bd6549f260f0d6c7459f5d86f3bf1679be3177ef795b2f24513146a32bc6850
    container_name: apprise_api
    restart: unless-stopped
    volumes:
      # Relative path: Points directly to a 'config' folder inside your GitHub repo clone
      - ./config:/config
    environment:
      - PUID=99   # Keeps Unraid file permissions happy
      - PGID=100
      - TZ=${TZ}
      - APPRISE_CONFIG=${APPRISE_CONFIG}
      - APPRISE_WEBHOOK_TOKEN=${APPRISE_WEBHOOK_TOKEN}
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apprise.rule=Host(`notify.theblaskies.com`)"
      - "traefik.http.routers.apprise.entrypoints=websecure"
      - "traefik.http.routers.apprise.tls.certresolver=cloudflare"
      - "traefik.http.services.apprise.loadbalancer.server.port=8000"

networks:
  proxy_net:
    external: true
